import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.screenshot({ path: '/home/user/PulseAIRepo/ui/screenshots/agent-ui-1440x900.png' });
await p.getByRole('button', { name: /Agent Manager/ }).click();
await p.waitForTimeout(1200);
await p.screenshot({ path: '/home/user/PulseAIRepo/ui/screenshots/manager-1440x900.png' });
await b.close();
